### ISSUE TITLE
Upgraded to Version 2

### ISSUE THREAD

**Issue by copytec11** [markhannon/zimi-integration#30]
I finally got around to upgrading to version 2 having to use the BLE Mac Address and not the wifi Mac Address but the actual door just says not Provided

![Image](https://github.com/user-attachments/assets/f287b6c4-c463-43a8-b836-2eb0b8e2a5de)

**Comment by copytec11** [comment]
Is there any reason why no matter what I do any version of version 2 does not work for me

**Comment by markhannon** [comment]
If it worked earlier I don’t see any reason it would not work now.     Can
you enable debug on the integration, restart HA and send the control point
summary printout from the logs please?

**Comment by copytec11** [comment]
Hay Mark, thanks for the reply. I know time is value. Just so you know I have never got Version 2 to work.. At first it wasn't accepting the mac address but then I tried it with the ble mac address and I got the integration to install but no door. As in not available... I have no idea what is going on with it.

**Comment by markhannon** [comment]
Can you try to delete the integration and downgrade to the latest version 1 please?

The only garage feature you would lose is the small buffer on open and close % that I implemented for someone that was having problems.  

There shouldn't be any other differences once the integration is configured but best to check!

(BTW the configuration flow for version 2 is under active fine tuning with the HA review.   Once it stabilises I will release a new version of it for the HACS repo)

**Comment by copytec11** [comment]
That was me also have the problem of not showing closed but I never managed to get v2 working so I am back on 1.43 but still have the not closed problem...

**Comment by markhannon** [comment]
For the closed problem you can edit the lights.py file yourself - you need the **or self.device.percentage** clauses as per below.   I don't plan to backport this.

```
    @property
    def is_closed(self) -> bool | None:
        """Return true if cover is closed."""
        return self._device.is_closed or self._device.percentage < 5

    @property
    def is_open(self) -> bool | None:
        """Return true if cover is open."""
        return self._device.is_open or self._device.percentage > 95
```

For the V1 vs V2 problem I am stumped - can you enable debug and send me a the log of the restart so that I can see the messages and the text summary of the zcc please?

**Comment by markhannon** [comment]
Addendum ... the file to edit is cover.py and the version 1 branch is a little different.   It should be changed to:

```
    @property
    def is_closed(self) -> bool | None:
        """Return true if cover is closed."""
        return self._cover.is_closed or self._cover.percentage < 5

    @property
    def is_open(self) -> bool | None:
        """Return true if cover is open."""
        return self._cover.is_open  or self._cover.percentage > 95
```

**Comment by copytec11** [comment]
I will try later as for right now I need the door to open and close via HA but when I have some time I will try again.. Thanks again for taking time to answer questions

**Comment by copytec11** [comment]
Just updated to v2.0 dev 5 and my garage door now works fine ...thanks for the update

**Comment by markhannon** [comment]
Great.  Was the config flow simpler with no need to manually populate data?

**Comment by copytec11** [comment]
I simply udpated it from V2.0 to Dev5 and it worked. I did have to do anything else
